title: "Rajat Joshi"
description: "PhD Candidate"
url: "https://rajatjoshi8.github.io/rajatjoshi.github.io/"
theme: minimal-mistakes
repository: rajatjoshi8/rajatjoshi.github.io

# Navigation Links
header_pages: 
  - index.md
  - about.md
  - projects.md
  - contact.md

# Social Links
author:
  name: "Rajat Joshi"
  avatar: "https://raw.githubusercontent.com/rajatjoshi8/rajatjoshi.github.io/main/IMG-3026.jpg"
  scholar: "https://scholar.google.com/citations?user=FVbbAZMAAAAJ&hl=en"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
