title: "Rajat Joshi"
description: "PhD Candidate"
url: "https://rajatjoshi8.github.io/rajatjoshi.github.io"
theme: jekyll-theme-cayman
#repository: rajatjoshi8/rajatjoshi.github.io

# Navigation Links
header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md

# Social Links
author:
  name: "Rajat Joshi"
  avatar: "https://raw.githubusercontent.com/rajatjoshi8/rajatjoshi.github.io/main/assets/Profile_image.jpg"
  scholar: "https://scholar.google.com/citations?user=FVbbAZMAAAAJ&hl=en"
  #linkedin: "https://www.linkedin.com/in/rajat-joshi/"
  #cv: "assets/CV_Rajat_Joshi.pdf"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
